0|server  | <ref *2> IncomingMessage {
0|server  |   _readableState: ReadableState {
0|server  |     highWaterMark: 16384,
0|server  |     buffer: BufferList { head: null, tail: null, length: 0 },
0|server  |     length: 0,
0|server  |     pipes: [],
0|server  |     awaitDrainWriters: null,
0|server  |     [Symbol(kState)]: 1185842
0|server  |   },
0|server  |   _events: [Object: null prototype] {},
0|server  |   _eventsCount: 0,
0|server  |   _maxListeners: undefined,
0|server  |   socket: <ref *1> Socket {
0|server  |     connecting: false,
0|server  |     _hadError: false,
0|server  |     _parent: null,
0|server  |     _host: null,
0|server  |     _closeAfterHandlingError: false,
0|server  |     _readableState: ReadableState {
0|server  |       highWaterMark: 16384,
0|server  |       buffer: BufferList { head: null, tail: null, length: 0 },
0|server  |       length: 0,
0|server  |       pipes: [],
0|server  |       awaitDrainWriters: null,
0|server  |       [Symbol(kState)]: 59773016
0|server  |     },
0|server  |     _events: [Object: null prototype] {
0|server  |       end: [Array],
0|server  |       timeout: [Function: socketOnTimeout],
0|server  |       data: [Function: bound socketOnData],
0|server  |       error: [Function: socketOnError],
0|server  |       close: [Array],
0|server  |       drain: [Function: bound socketOnDrain],
0|server  |       resume: [Function: onSocketResume],
0|server  |       pause: [Function: onSocketPause]
0|server  |     },
0|server  |     _eventsCount: 8,
0|server  |     _maxListeners: undefined,
0|server  |     _writableState: WritableState {
0|server  |       highWaterMark: 16384,
0|server  |       length: 0,
0|server  |       corked: 0,
0|server  |       onwrite: [Function: bound onwrite],
0|server  |       writelen: 0,
0|server  |       bufferedIndex: 0,
0|server  |       pendingcb: 0,
0|server  |       [Symbol(kState)]: 34340940,
0|server  |       [Symbol(kBufferedValue)]: null
0|server  |     },
0|server  |     allowHalfOpen: true,
0|server  |     _sockname: null,
0|server  |     _pendingData: null,
0|server  |     _pendingEncoding: '',
0|server  |     server: Server {
0|server  |       maxHeaderSize: undefined,
0|server  |       insecureHTTPParser: undefined,
0|server  |       requestTimeout: 300000,
0|server  |       headersTimeout: 60000,
0|server  |       keepAliveTimeout: 5000,
0|server  |       connectionsCheckingInterval: 30000,
0|server  |       requireHostHeader: true,
0|server  |       joinDuplicateHeaders: undefined,
0|server  |       rejectNonStandardBodyWrites: false,
0|server  |       _events: [Object: null prototype],
0|server  |       _eventsCount: 3,
0|server  |       _maxListeners: undefined,
0|server  |       _connections: 1,
0|server  |       _handle: [TCP],
0|server  |       _usingWorkers: false,
0|server  |       _workers: [],
0|server  |       _unref: false,
0|server  |       allowHalfOpen: true,
0|server  |       pauseOnConnect: false,
0|server  |       noDelay: true,
0|server  |       keepAlive: false,
0|server  |       keepAliveInitialDelay: 0,
0|server  |       highWaterMark: 16384,
0|server  |       httpAllowHalfOpen: false,
0|server  |       timeout: 0,
0|server  |       maxHeadersCount: null,
0|server  |       maxRequestsPerSocket: 0,
0|server  |       _connectionKey: '6::::5050',
0|server  |       [Symbol(IncomingMessage)]: [Function: IncomingMessage],
0|server  |       [Symbol(ServerResponse)]: [Function: ServerResponse],
0|server  |       [Symbol(kCapture)]: false,
0|server  |       [Symbol(async_id_symbol)]: 111,
0|server  |       [Symbol(kUniqueHeaders)]: null,
0|server  |       [Symbol(http.server.connections)]: ConnectionsList {},
0|server  |       [Symbol(http.server.connectionsCheckingInterval)]: Timeout {
0|server  |         _idleTimeout: 30000,
0|server  |         _idlePrev: [TimersList],
0|server  |         _idleNext: [TimersList],
0|server  |         _idleStart: 331084,
0|server  |         _onTimeout: [Function: bound checkConnections],
0|server  |         _timerArgs: undefined,
0|server  |         _repeat: 30000,
0|server  |         _destroyed: false,
0|server  |         [Symbol(refed)]: false,
0|server  |         [Symbol(kHasPrimitive)]: false,
0|server  |         [Symbol(asyncId)]: 113,
0|server  |         [Symbol(triggerId)]: 112
0|server  |       }
0|server  |     },
0|server  |     _server: Server {
0|server  |       maxHeaderSize: undefined,
0|server  |       insecureHTTPParser: undefined,
0|server  |       requestTimeout: 300000,
0|server  |       headersTimeout: 60000,
0|server  |       keepAliveTimeout: 5000,
0|server  |       connectionsCheckingInterval: 30000,
0|server  |       requireHostHeader: true,
0|server  |       joinDuplicateHeaders: undefined,
0|server  |       rejectNonStandardBodyWrites: false,
0|server  |       _events: [Object: null prototype],
0|server  |       _eventsCount: 3,
0|server  |       _maxListeners: undefined,
0|server  |       _connections: 1,
0|server  |       _handle: [TCP],
0|server  |       _usingWorkers: false,
0|server  |       _workers: [],
0|server  |       _unref: false,
0|server  |       allowHalfOpen: true,
0|server  |       pauseOnConnect: false,
0|server  |       noDelay: true,
0|server  |       keepAlive: false,
0|server  |       keepAliveInitialDelay: 0,
0|server  |       highWaterMark: 16384,
0|server  |       httpAllowHalfOpen: false,
0|server  |       timeout: 0,
0|server  |       maxHeadersCount: null,
0|server  |       maxRequestsPerSocket: 0,
0|server  |       _connectionKey: '6::::5050',
0|server  |       [Symbol(IncomingMessage)]: [Function: IncomingMessage],
0|server  |       [Symbol(ServerResponse)]: [Function: ServerResponse],
0|server  |       [Symbol(kCapture)]: false,
0|server  |       [Symbol(async_id_symbol)]: 111,
0|server  |       [Symbol(kUniqueHeaders)]: null,
0|server  |       [Symbol(http.server.connections)]: ConnectionsList {},
0|server  |       [Symbol(http.server.connectionsCheckingInterval)]: Timeout {
0|server  |         _idleTimeout: 30000,
0|server  |         _idlePrev: [TimersList],
0|server  |         _idleNext: [TimersList],
0|server  |         _idleStart: 331084,
0|server  |         _onTimeout: [Function: bound checkConnections],
0|server  |         _timerArgs: undefined,
0|server  |         _repeat: 30000,
0|server  |         _destroyed: false,
0|server  |         [Symbol(refed)]: false,
0|server  |         [Symbol(kHasPrimitive)]: false,
0|server  |         [Symbol(asyncId)]: 113,
0|server  |         [Symbol(triggerId)]: 112
0|server  |       }
0|server  |     },
0|server  |     parser: HTTPParser {
0|server  |       '0': null,
0|server  |       '1': [Function: parserOnHeaders],
0|server  |       '2': [Function: parserOnHeadersComplete],
0|server  |       '3': [Function: parserOnBody],
0|server  |       '4': [Function: parserOnMessageComplete],
0|server  |       '5': [Function: bound onParserExecute],
0|server  |       '6': [Function: bound onParserTimeout],
0|server  |       _headers: [],
0|server  |       _url: '',
0|server  |       socket: [Circular *1],
0|server  |       incoming: [Circular *2],
0|server  |       outgoing: null,
0|server  |       maxHeaderPairs: 2000,
0|server  |       _consumed: true,
0|server  |       onIncoming: [Function: bound parserOnIncoming],
0|server  |       joinDuplicateHeaders: null,
0|server  |       [Symbol(resource_symbol)]: [HTTPServerAsyncResource]
0|server  |     },
0|server  |     on: [Function: socketListenerWrap],
0|server  |     addListener: [Function: socketListenerWrap],
0|server  |     prependListener: [Function: socketListenerWrap],
0|server  |     setEncoding: [Function: socketSetEncoding],
0|server  |     _paused: false,
0|server  |     _httpMessage: ServerResponse {
0|server  |       _events: [Object: null prototype],
0|server  |       _eventsCount: 1,
0|server  |       _maxListeners: undefined,
0|server  |       outputData: [],
0|server  |       outputSize: 0,
0|server  |       writable: true,
0|server  |       destroyed: false,
0|server  |       _last: false,
0|server  |       chunkedEncoding: false,
0|server  |       shouldKeepAlive: true,
0|server  |       maxRequestsOnConnectionReached: false,
0|server  |       _defaultKeepAlive: true,
0|server  |       useChunkedEncodingByDefault: true,
0|server  |       sendDate: true,
0|server  |       _removedConnection: false,
0|server  |       _removedContLen: false,
0|server  |       _removedTE: false,
0|server  |       strictContentLength: false,
0|server  |       _contentLength: null,
0|server  |       _hasBody: true,
0|server  |       _trailer: '',
0|server  |       finished: false,
0|server  |       _headerSent: false,
0|server  |       _closed: false,
0|server  |       socket: [Circular *1],
0|server  |       _header: null,
0|server  |       _keepAliveTimeout: 5000,
0|server  |       _onPendingData: [Function: bound updateOutgoingData],
0|server  |       req: [Circular *2],
0|server  |       _sent100: false,
0|server  |       _expect_continue: false,
0|server  |       _maxRequestsPerSocket: 0,
0|server  |       locals: [Object: null prototype] {},
0|server  |       [Symbol(kCapture)]: false,
0|server  |       [Symbol(kBytesWritten)]: 0,
0|server  |       [Symbol(kNeedDrain)]: false,
0|server  |       [Symbol(corked)]: 0,
0|server  |       [Symbol(kOutHeaders)]: [Object: null prototype],
0|server  |       [Symbol(errored)]: null,
0|server  |       [Symbol(kHighWaterMark)]: 16384,
0|server  |       [Symbol(kRejectNonStandardBodyWrites)]: false,
0|server  |       [Symbol(kUniqueHeaders)]: null
0|server  |     },
0|server  |     [Symbol(async_id_symbol)]: 1736,
0|server  |     [Symbol(kHandle)]: TCP {
0|server  |       reading: true,
0|server  |       onconnection: null,
0|server  |       _consumed: true,
0|server  |       [Symbol(owner_symbol)]: [Circular *1]
0|server  |     },
0|server  |     [Symbol(lastWriteQueueSize)]: 0,
0|server  |     [Symbol(timeout)]: null,
0|server  |     [Symbol(kBuffer)]: null,
0|server  |     [Symbol(kBufferCb)]: null,
0|server  |     [Symbol(kBufferGen)]: null,
0|server  |     [Symbol(kCapture)]: false,
0|server  |     [Symbol(kSetNoDelay)]: true,
0|server  |     [Symbol(kSetKeepAlive)]: false,
0|server  |     [Symbol(kSetKeepAliveInitialDelay)]: 0,
0|server  |     [Symbol(kBytesRead)]: 0,
0|server  |     [Symbol(kBytesWritten)]: 0
0|server  |   },
0|server  |   httpVersionMajor: 1,
0|server  |   httpVersionMinor: 1,
0|server  |   httpVersion: '1.1',
0|server  |   complete: true,
0|server  |   rawHeaders: [
0|server  |     'Connection',
0|server  |     'upgrade',
0|server  |     'Host',
0|server  |     'gum.lk',
0|server  |     'accept-encoding',
0|server  |     'gzip',
0|server  |     'X-Forwarded-For',
0|server  |     '184.145.40.103',
0|server  |     'CF-RAY',
0|server  |     '83846aa11cada252-FRA',
0|server  |     'X-Forwarded-Proto',
0|server  |     'https',
0|server  |     'CF-Visitor',
0|server  |     '{"scheme":"https"}',
0|server  |     'accept',
0|server  |     'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
0|server  |     'sec-fetch-site',
0|server  |     'none',
0|server  |     'priority',
0|server  |     'u=0, i',
0|server  |     'upgrade-insecure-requests',
0|server  |     '1',
0|server  |     'sec-fetch-mode',
0|server  |     'navigate',
0|server  |     'user-agent',
0|server  |     'Mozilla/5.0 (iPhone; CPU iPhone OS 17_1_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148',
0|server  |     'accept-language',
0|server  |     'en-CA,en-US;q=0.9,en;q=0.8',
0|server  |     'sec-fetch-dest',
0|server  |     'document',
0|server  |     'CF-Connecting-IP',
0|server  |     '184.145.40.103',
0|server  |     'CDN-Loop',
0|server  |     'cloudflare',
0|server  |     'CF-IPCountry',
0|server  |     'CA'
0|server  |   ],
0|server  |   rawTrailers: [],
0|server  |   joinDuplicateHeaders: null,
0|server  |   aborted: false,
0|server  |   upgrade: false,
0|server  |   url: '/kq3vw8jxjxjxjxj?fbclid=PAAaY5UEvWQtZ2FK1OCQbNg2jjjNpAbI0v4cHKCyWyTFjHUS9eRZKhxiC8mvc_aem_AcGi0vpXJtFrtYQtKaRjYtEZvICiyE2du991jCNSvP0LyLGMd5uH8NGnSQl4PW4RsFY',
0|server  |   method: 'GET',
0|server  |   statusCode: null,
0|server  |   statusMessage: null,
0|server  |   client: <ref *1> Socket {
0|server  |     connecting: false,
0|server  |     _hadError: false,
0|server  |     _parent: null,
0|server  |     _host: null,
0|server  |     _closeAfterHandlingError: false,
0|server  |     _readableState: ReadableState {
0|server  |       highWaterMark: 16384,
0|server  |       buffer: BufferList { head: null, tail: null, length: 0 },
0|server  |       length: 0,
0|server  |       pipes: [],
0|server  |       awaitDrainWriters: null,
0|server  |       [Symbol(kState)]: 59773016
0|server  |     },
0|server  |     _events: [Object: null prototype] {
0|server  |       end: [Array],
0|server  |       timeout: [Function: socketOnTimeout],
0|server  |       data: [Function: bound socketOnData],
0|server  |       error: [Function: socketOnError],
0|server  |       close: [Array],
0|server  |       drain: [Function: bound socketOnDrain],
0|server  |       resume: [Function: onSocketResume],
0|server  |       pause: [Function: onSocketPause]
0|server  |     },
0|server  |     _eventsCount: 8,
0|server  |     _maxListeners: undefined,
0|server  |     _writableState: WritableState {
0|server  |       highWaterMark: 16384,
0|server  |       length: 0,
0|server  |       corked: 0,
0|server  |       onwrite: [Function: bound onwrite],
0|server  |       writelen: 0,
0|server  |       bufferedIndex: 0,
0|server  |       pendingcb: 0,
0|server  |       [Symbol(kState)]: 34340940,
0|server  |       [Symbol(kBufferedValue)]: null
0|server  |     },
0|server  |     allowHalfOpen: true,
0|server  |     _sockname: null,
0|server  |     _pendingData: null,
0|server  |     _pendingEncoding: '',
0|server  |     server: Server {
0|server  |       maxHeaderSize: undefined,
0|server  |       insecureHTTPParser: undefined,
0|server  |       requestTimeout: 300000,
0|server  |       headersTimeout: 60000,
0|server  |       keepAliveTimeout: 5000,
0|server  |       connectionsCheckingInterval: 30000,
0|server  |       requireHostHeader: true,
0|server  |       joinDuplicateHeaders: undefined,
0|server  |       rejectNonStandardBodyWrites: false,
0|server  |       _events: [Object: null prototype],
0|server  |       _eventsCount: 3,
0|server  |       _maxListeners: undefined,
0|server  |       _connections: 1,
0|server  |       _handle: [TCP],
0|server  |       _usingWorkers: false,
0|server  |       _workers: [],
0|server  |       _unref: false,
0|server  |       allowHalfOpen: true,
0|server  |       pauseOnConnect: false,
0|server  |       noDelay: true,
0|server  |       keepAlive: false,
0|server  |       keepAliveInitialDelay: 0,
0|server  |       highWaterMark: 16384,
0|server  |       httpAllowHalfOpen: false,
0|server  |       timeout: 0,
0|server  |       maxHeadersCount: null,
0|server  |       maxRequestsPerSocket: 0,
0|server  |       _connectionKey: '6::::5050',
0|server  |       [Symbol(IncomingMessage)]: [Function: IncomingMessage],
0|server  |       [Symbol(ServerResponse)]: [Function: ServerResponse],
0|server  |       [Symbol(kCapture)]: false,
0|server  |       [Symbol(async_id_symbol)]: 111,
0|server  |       [Symbol(kUniqueHeaders)]: null,
0|server  |       [Symbol(http.server.connections)]: ConnectionsList {},
0|server  |       [Symbol(http.server.connectionsCheckingInterval)]: Timeout {
0|server  |         _idleTimeout: 30000,
0|server  |         _idlePrev: [TimersList],
0|server  |         _idleNext: [TimersList],
0|server  |         _idleStart: 331084,
0|server  |         _onTimeout: [Function: bound checkConnections],
0|server  |         _timerArgs: undefined,
0|server  |         _repeat: 30000,
0|server  |         _destroyed: false,
0|server  |         [Symbol(refed)]: false,
0|server  |         [Symbol(kHasPrimitive)]: false,
0|server  |         [Symbol(asyncId)]: 113,
0|server  |         [Symbol(triggerId)]: 112
0|server  |       }
0|server  |     },
0|server  |     _server: Server {
0|server  |       maxHeaderSize: undefined,
0|server  |       insecureHTTPParser: undefined,
0|server  |       requestTimeout: 300000,
0|server  |       headersTimeout: 60000,
0|server  |       keepAliveTimeout: 5000,
0|server  |       connectionsCheckingInterval: 30000,
0|server  |       requireHostHeader: true,
0|server  |       joinDuplicateHeaders: undefined,
0|server  |       rejectNonStandardBodyWrites: false,
0|server  |       _events: [Object: null prototype],
0|server  |       _eventsCount: 3,
0|server  |       _maxListeners: undefined,
0|server  |       _connections: 1,
0|server  |       _handle: [TCP],
0|server  |       _usingWorkers: false,
0|server  |       _workers: [],
0|server  |       _unref: false,
0|server  |       allowHalfOpen: true,
0|server  |       pauseOnConnect: false,
0|server  |       noDelay: true,
0|server  |       keepAlive: false,
0|server  |       keepAliveInitialDelay: 0,
0|server  |       highWaterMark: 16384,
0|server  |       httpAllowHalfOpen: false,
0|server  |       timeout: 0,
0|server  |       maxHeadersCount: null,
0|server  |       maxRequestsPerSocket: 0,
0|server  |       _connectionKey: '6::::5050',
0|server  |       [Symbol(IncomingMessage)]: [Function: IncomingMessage],
0|server  |       [Symbol(ServerResponse)]: [Function: ServerResponse],
0|server  |       [Symbol(kCapture)]: false,
0|server  |       [Symbol(async_id_symbol)]: 111,
0|server  |       [Symbol(kUniqueHeaders)]: null,
0|server  |       [Symbol(http.server.connections)]: ConnectionsList {},
0|server  |       [Symbol(http.server.connectionsCheckingInterval)]: Timeout {
0|server  |         _idleTimeout: 30000,
0|server  |         _idlePrev: [TimersList],
0|server  |         _idleNext: [TimersList],
0|server  |         _idleStart: 331084,
0|server  |         _onTimeout: [Function: bound checkConnections],
0|server  |         _timerArgs: undefined,
0|server  |         _repeat: 30000,
0|server  |         _destroyed: false,
0|server  |         [Symbol(refed)]: false,
0|server  |         [Symbol(kHasPrimitive)]: false,
0|server  |         [Symbol(asyncId)]: 113,
0|server  |         [Symbol(triggerId)]: 112
0|server  |       }
0|server  |     },
0|server  |     parser: HTTPParser {
0|server  |       '0': null,
0|server  |       '1': [Function: parserOnHeaders],
0|server  |       '2': [Function: parserOnHeadersComplete],
0|server  |       '3': [Function: parserOnBody],
0|server  |       '4': [Function: parserOnMessageComplete],
0|server  |       '5': [Function: bound onParserExecute],
0|server  |       '6': [Function: bound onParserTimeout],
0|server  |       _headers: [],
0|server  |       _url: '',
0|server  |       socket: [Circular *1],
0|server  |       incoming: [Circular *2],
0|server  |       outgoing: null,
0|server  |       maxHeaderPairs: 2000,
0|server  |       _consumed: true,
0|server  |       onIncoming: [Function: bound parserOnIncoming],
0|server  |       joinDuplicateHeaders: null,
0|server  |       [Symbol(resource_symbol)]: [HTTPServerAsyncResource]
0|server  |     },
0|server  |     on: [Function: socketListenerWrap],
0|server  |     addListener: [Function: socketListenerWrap],
0|server  |     prependListener: [Function: socketListenerWrap],
0|server  |     setEncoding: [Function: socketSetEncoding],
0|server  |     _paused: false,
0|server  |     _httpMessage: ServerResponse {
0|server  |       _events: [Object: null prototype],
0|server  |       _eventsCount: 1,
0|server  |       _maxListeners: undefined,
0|server  |       outputData: [],
0|server  |       outputSize: 0,
0|server  |       writable: true,
0|server  |       destroyed: false,
0|server  |       _last: false,
0|server  |       chunkedEncoding: false,
0|server  |       shouldKeepAlive: true,
0|server  |       maxRequestsOnConnectionReached: false,
0|server  |       _defaultKeepAlive: true,
0|server  |       useChunkedEncodingByDefault: true,
0|server  |       sendDate: true,
0|server  |       _removedConnection: false,
0|server  |       _removedContLen: false,
0|server  |       _removedTE: false,
0|server  |       strictContentLength: false,
0|server  |       _contentLength: null,
0|server  |       _hasBody: true,
0|server  |       _trailer: '',
0|server  |       finished: false,
0|server  |       _headerSent: false,
0|server  |       _closed: false,
0|server  |       socket: [Circular *1],
0|server  |       _header: null,
0|server  |       _keepAliveTimeout: 5000,
0|server  |       _onPendingData: [Function: bound updateOutgoingData],
0|server  |       req: [Circular *2],
0|server  |       _sent100: false,
0|server  |       _expect_continue: false,
0|server  |       _maxRequestsPerSocket: 0,
0|server  |       locals: [Object: null prototype] {},
0|server  |       [Symbol(kCapture)]: false,
0|server  |       [Symbol(kBytesWritten)]: 0,
0|server  |       [Symbol(kNeedDrain)]: false,
0|server  |       [Symbol(corked)]: 0,
0|server  |       [Symbol(kOutHeaders)]: [Object: null prototype],
0|server  |       [Symbol(errored)]: null,
0|server  |       [Symbol(kHighWaterMark)]: 16384,
0|server  |       [Symbol(kRejectNonStandardBodyWrites)]: false,
0|server  |       [Symbol(kUniqueHeaders)]: null
0|server  |     },
0|server  |     [Symbol(async_id_symbol)]: 1736,
0|server  |     [Symbol(kHandle)]: TCP {
0|server  |       reading: true,
0|server  |       onconnection: null,
0|server  |       _consumed: true,
0|server  |       [Symbol(owner_symbol)]: [Circular *1]
0|server  |     },
0|server  |     [Symbol(lastWriteQueueSize)]: 0,
0|server  |     [Symbol(timeout)]: null,
0|server  |     [Symbol(kBuffer)]: null,
0|server  |     [Symbol(kBufferCb)]: null,
0|server  |     [Symbol(kBufferGen)]: null,
0|server  |     [Symbol(kCapture)]: false,
0|server  |     [Symbol(kSetNoDelay)]: true,
0|server  |     [Symbol(kSetKeepAlive)]: false,
0|server  |     [Symbol(kSetKeepAliveInitialDelay)]: 0,
0|server  |     [Symbol(kBytesRead)]: 0,
0|server  |     [Symbol(kBytesWritten)]: 0
0|server  |   },
0|server  |   _consuming: false,
0|server  |   _dumped: false,
0|server  |   next: [Function: next],
0|server  |   baseUrl: '',
0|server  |   originalUrl: '/kq3vw8jxjxjxjxj?fbclid=PAAaY5UEvWQtZ2FK1OCQbNg2jjjNpAbI0v4cHKCyWyTFjHUS9eRZKhxiC8mvc_aem_AcGi0vpXJtFrtYQtKaRjYtEZvICiyE2du991jCNSvP0LyLGMd5uH8NGnSQl4PW4RsFY',
0|server  |   _parsedUrl: Url {
0|server  |     protocol: null,
0|server  |     slashes: null,
0|server  |     auth: null,
0|server  |     host: null,
0|server  |     port: null,
0|server  |     hostname: null,
0|server  |     hash: null,
0|server  |     search: '?fbclid=PAAaY5UEvWQtZ2FK1OCQbNg2jjjNpAbI0v4cHKCyWyTFjHUS9eRZKhxiC8mvc_aem_AcGi0vpXJtFrtYQtKaRjYtEZvICiyE2du991jCNSvP0LyLGMd5uH8NGnSQl4PW4RsFY',
0|server  |     query: 'fbclid=PAAaY5UEvWQtZ2FK1OCQbNg2jjjNpAbI0v4cHKCyWyTFjHUS9eRZKhxiC8mvc_aem_AcGi0vpXJtFrtYQtKaRjYtEZvICiyE2du991jCNSvP0LyLGMd5uH8NGnSQl4PW4RsFY',
0|server  |     pathname: '/kq3vw8jxjxjxjxj',
0|server  |     path: '/kq3vw8jxjxjxjxj?fbclid=PAAaY5UEvWQtZ2FK1OCQbNg2jjjNpAbI0v4cHKCyWyTFjHUS9eRZKhxiC8mvc_aem_AcGi0vpXJtFrtYQtKaRjYtEZvICiyE2du991jCNSvP0LyLGMd5uH8NGnSQl4PW4RsFY',
0|server  |     href: '/kq3vw8jxjxjxjxj?fbclid=PAAaY5UEvWQtZ2FK1OCQbNg2jjjNpAbI0v4cHKCyWyTFjHUS9eRZKhxiC8mvc_aem_AcGi0vpXJtFrtYQtKaRjYtEZvICiyE2du991jCNSvP0LyLGMd5uH8NGnSQl4PW4RsFY',
0|server  |     _raw: '/kq3vw8jxjxjxjxj?fbclid=PAAaY5UEvWQtZ2FK1OCQbNg2jjjNpAbI0v4cHKCyWyTFjHUS9eRZKhxiC8mvc_aem_AcGi0vpXJtFrtYQtKaRjYtEZvICiyE2du991jCNSvP0LyLGMd5uH8NGnSQl4PW4RsFY'
0|server  |   },
0|server  |   params: { linkkey: 'kq3vw8jxjxjxjxj' },
0|server  |   query: {
0|server  |     fbclid: 'PAAaY5UEvWQtZ2FK1OCQbNg2jjjNpAbI0v4cHKCyWyTFjHUS9eRZKhxiC8mvc_aem_AcGi0vpXJtFrtYQtKaRjYtEZvICiyE2du991jCNSvP0LyLGMd5uH8NGnSQl4PW4RsFY'
0|server  |   },
0|server  |   res: <ref *3> ServerResponse {
0|server  |     _events: [Object: null prototype] { finish: [Array] },
0|server  |     _eventsCount: 1,
0|server  |     _maxListeners: undefined,
0|server  |     outputData: [],
0|server  |     outputSize: 0,
0|server  |     writable: true,
0|server  |     destroyed: false,
0|server  |     _last: false,
0|server  |     chunkedEncoding: false,
0|server  |     shouldKeepAlive: true,
0|server  |     maxRequestsOnConnectionReached: false,
0|server  |     _defaultKeepAlive: true,
0|server  |     useChunkedEncodingByDefault: true,
0|server  |     sendDate: true,
0|server  |     _removedConnection: false,
0|server  |     _removedContLen: false,
0|server  |     _removedTE: false,
0|server  |     strictContentLength: false,
0|server  |     _contentLength: null,
0|server  |     _hasBody: true,
0|server  |     _trailer: '',
0|server  |     finished: false,
0|server  |     _headerSent: false,
0|server  |     _closed: false,
0|server  |     socket: <ref *1> Socket {
0|server  |       connecting: false,
0|server  |       _hadError: false,
0|server  |       _parent: null,
0|server  |       _host: null,
0|server  |       _closeAfterHandlingError: false,
0|server  |       _readableState: [ReadableState],
0|server  |       _events: [Object: null prototype],
0|server  |       _eventsCount: 8,
0|server  |       _maxListeners: undefined,
0|server  |       _writableState: [WritableState],
0|server  |       allowHalfOpen: true,
0|server  |       _sockname: null,
0|server  |       _pendingData: null,
0|server  |       _pendingEncoding: '',
0|server  |       server: [Server],
0|server  |       _server: [Server],
0|server  |       parser: [HTTPParser],
0|server  |       on: [Function: socketListenerWrap],
0|server  |       addListener: [Function: socketListenerWrap],
0|server  |       prependListener: [Function: socketListenerWrap],
0|server  |       setEncoding: [Function: socketSetEncoding],
0|server  |       _paused: false,
0|server  |       _httpMessage: [Circular *3],
0|server  |       [Symbol(async_id_symbol)]: 1736,
0|server  |       [Symbol(kHandle)]: [TCP],
0|server  |       [Symbol(lastWriteQueueSize)]: 0,
0|server  |       [Symbol(timeout)]: null,
0|server  |       [Symbol(kBuffer)]: null,
0|server  |       [Symbol(kBufferCb)]: null,
0|server  |       [Symbol(kBufferGen)]: null,
0|server  |       [Symbol(kCapture)]: false,
0|server  |       [Symbol(kSetNoDelay)]: true,
0|server  |       [Symbol(kSetKeepAlive)]: false,
0|server  |       [Symbol(kSetKeepAliveInitialDelay)]: 0,
0|server  |       [Symbol(kBytesRead)]: 0,
0|server  |       [Symbol(kBytesWritten)]: 0
0|server  |     },
0|server  |     _header: null,
0|server  |     _keepAliveTimeout: 5000,
0|server  |     _onPendingData: [Function: bound updateOutgoingData],
0|server  |     req: [Circular *2],
0|server  |     _sent100: false,
0|server  |     _expect_continue: false,
0|server  |     _maxRequestsPerSocket: 0,
0|server  |     locals: [Object: null prototype] {},
0|server  |     [Symbol(kCapture)]: false,
0|server  |     [Symbol(kBytesWritten)]: 0,
0|server  |     [Symbol(kNeedDrain)]: false,
0|server  |     [Symbol(corked)]: 0,
0|server  |     [Symbol(kOutHeaders)]: [Object: null prototype] {
0|server  |       'x-powered-by': [Array],
0|server  |       'access-control-allow-origin': [Array]
0|server  |     },
0|server  |     [Symbol(errored)]: null,
0|server  |     [Symbol(kHighWaterMark)]: 16384,
0|server  |     [Symbol(kRejectNonStandardBodyWrites)]: false,
0|server  |     [Symbol(kUniqueHeaders)]: null
0|server  |   },
0|server  |   body: {},
0|server  |   route: Route {
0|server  |     path: '/:linkkey',
0|server  |     stack: [ [Layer], [Layer] ],
0|server  |     methods: { get: true }
0|server  |   },
0|server  |   linkDetails: {
0|server  |     city: 'Toronto',
0|server  |     region: 'ON',
0|server  |     country: 'CA',
0|server  |     device: 'Mobile',
0|server  |     browser: 'Apple WebKit',
0|server  |     os: 'OS X',
0|server  |     referrer: ''
0|server  |   },
0|server  |   [Symbol(kCapture)]: false,
0|server  |   [Symbol(kHeaders)]: {
0|server  |     connection: 'upgrade',
0|server  |     host: 'gum.lk',
0|server  |     'accept-encoding': 'gzip',
0|server  |     'x-forwarded-for': '184.145.40.103',
0|server  |     'cf-ray': '83846aa11cada252-FRA',
0|server  |     'x-forwarded-proto': 'https',
0|server  |     'cf-visitor': '{"scheme":"https"}',
0|server  |     accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
0|server  |     'sec-fetch-site': 'none',
0|server  |     priority: 'u=0, i',
0|server  |     'upgrade-insecure-requests': '1',
0|server  |     'sec-fetch-mode': 'navigate',
0|server  |     'user-agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_1_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148',
0|server  |     'accept-language': 'en-CA,en-US;q=0.9,en;q=0.8',
0|server  |     'sec-fetch-dest': 'document',
0|server  |     'cf-connecting-ip': '184.145.40.103',
0|server  |     'cdn-loop': 'cloudflare',
0|server  |     'cf-ipcountry': 'CA'
0|server  |   },
0|server  |   [Symbol(kHeadersCount)]: 36,
0|server  |   [Symbol(kTrailers)]: null,
0|server  |   [Symbol(kTrailersCount)]: 0
0|server  | }